// import "../styles/global.css";
import Head from "next/head";
import Header from "../components/Header";

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <meta name="E-commerce" />
      </Head>
      <Header />
      <main className="flex flex-col px-[15.5%] bg-[#EFFCF6] h-max phones:justify-center">
        {children}
      </main>
    </>
  );
}
