// import "../styles/global.css";
import Head from "next/head";
import Header from "../components/Header";

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <meta name="E-commerce" />
      </Head>

      <main>
        <Header />
        <div className="flex flex-col py-20 px-[15.5%] bg-[#EFFCF6] min-h-screen responsive:justify-center responsive:px-[4%]">
          {children}
        </div>
      </main>
    </>
  );
}
